name: boundary-condition

version: '3'

networks:
  loki:
    driver: bridge

services:
  app:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./src:/app/src
    environment:
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_PORT: ${CLIENT_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SYNC: ${POSTGRES_SYNC}
      GF_USER: ${GF_USER}
      GF_PASSWORD: ${GF_PASSWORD}

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    command: '--config.file=/etc/promtail/promtail-config.yaml'
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./logs:/logs
      - ./logs/postgres-log:/var/log/postgresql
    restart: always
    depends_on:
      - prometheus
    networks:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:latest
    user: root
    command: '--config.file=/etc/loki/loki-config.yaml'
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki:/loki
    ports:
      - '3100:3100'
    restart: always
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASSWORD}
    env_file:
      - .env
    networks:
      - loki

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - loki

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - loki
