server:
  http_listen_port: 9080
  profiling_enabled: true

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: app_error_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/error/*.log
  - job_name: app_info_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/info/*.log
  - job_name: postgres_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: ./logs/postgres/*.log
