server:
  http_listen_port: 9080
  profiling_enabled: true

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/error/*.log
  - job_name: warn
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/warn/*.log
  - job_name: info
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/info/*.log
  - job_name: debug
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/debug/*.log
  - job_name: http
    static_configs:
      - targets:
          - localhost
        labels:
          job: winston
          __path__: ./logs/http/*.log
  - job_name: postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: ./logs/postgres/*.log
