# name: Nestjs CI
# name: Nestjs CI

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         node-version: [16.x, 18.x, 20.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20.x
#       - name: Install dependencies
#         run: npm ci
#       - name: Run lint
#         run: npm run lint
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         node-version: [16.x, 18.x, 20.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20.x
#       - name: Install dependencies
#         run: npm ci
#       - name: Run lint
#         run: npm run lint

#   # test:
#   #   needs: lint
#   #   runs-on: ubuntu-latest
#   #   strategy:
#   #     fail-fast: false
#   #     matrix:
#   #       node-version: [16.x, 18.x, 20.x]
#   #   steps:
#   #     - uses: actions/checkout@v2
#   #     - name: Use Node.js ${{ matrix.node-version }}
#   #       uses: actions/setup-node@v2
#   #       with:
#   #         node-version: ${{ matrix.node-version }}
#   #     - name: Install dependencies
#   #       run: npm ci
#   #     - name: Run lint
#   #       run: npm run lint
#   #     - name: Run tests
#   #       run: npm test

#    deploy:
#     # needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Deploy to Vultr "air"
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.SSH_PASSWORD}}

#           script: |
#             cd boundary-condition
#             git pull origin main
#             npm run build
#             pm2 reload 0
